### ISSUE TITLE
Lỗi module law trong phần quản trị

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/module-laws#1]
Sau khi thêm văn bản; tiến hành click nút Thực hiện thì nút chuyển sang mờ và đứng im, không có hiệu lực
![3](https://cloud.githubusercontent.com/assets/11238423/14200960/ee5c835c-f818-11e5-940d-1019ac7e8314.jpg)

**Comment by tntrucsp2** [comment]
Mình cũng thấy như vậy, Click chuột vào nút Thực hiện là đứng im luôn

**Comment by hoangphucvl88** [comment]
Mình cũng gặp lỗi này, Click chuột vào ## **nút Thực hiện là đứng im luôn.**

**Comment by HoanDateh** [comment]
Không thêm mới được văn bản
Phiên bản NukeViet	4.0.27
Phiên bản PHP	5.6.15
Giao thức giữa máy chủ và PHP	Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.15, apache2handler
Hệ điều hành máy chủ	WINDOWS NT
Phiên bản Database	mysql 5.5.5-10.1.10-MariaDB

**Comment by hoaquynhtim99** [comment]
Phần thêm văn bản hiện đang submit hoàn toàn bằng ajax nên sẽ khá nặng đối với những máy có cấu hình thấp, các bạn debug thử có lỗi 500 từ server không

**Comment by anhyeuviolet** [comment]
```
<br />
<b>Notice</b>:  SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 1 in <b>D:\xampp\htdocs\427\vendor\vinades\nukeviet\Core\Database.php</b> on line <b>109</b><br />
<br />
<b>Fatal error</b>:  Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1' in D:\xampp\htdocs\427\modules\laws\admin\main.php:370
Stack trace:
#0 D:\xampp\htdocs\427\modules\laws\admin\main.php(370): PDO-&gt;query('UPDATE nv4_vi_l...')
#1 D:\xampp\htdocs\427\admin\index.php(180): require('D:\\xampp\\htdocs...')
#2 {main}
  thrown in <b>D:\xampp\htdocs\427\modules\laws\admin\main.php</b> on line <b>370</b><br />
```
Debug ra quả này.

**Comment by vuthao** [comment]
Hiện tại mình đã sửa lại file cài đặt, các bạn có thể tải lại file https://github.com/nukeviet/module-laws/blob/master/modules/laws/action_mysql.php, sau đó cài lại module.

nếu đã nhập liệu rồi, trong thư mục document có file laws.to4.0.27.php, Copy file laws.to4.0.27.php ra trang chủ site rồi chay file đó  bằng cách truy cập http://domain_cua_ban/laws.to4.0.27.php

**Comment by hoanglongvnpt** [comment]
Lại xuất hiện lỗi cơ chế đếm của block **module block area top10 center** 
![10](https://cloud.githubusercontent.com/assets/11238423/14340754/dbf4c5a8-fcb4-11e5-8531-56df1f04c5ef.png)
trong lúc mình mới chỉ đăng ở 2 lĩnh vực 2 văn bản để test thử thôi. Mong được pix sớm. Thank

**Comment by tntrucsp2** [comment]
Khi xem chi tiết bị lỗi 500 vuthao ạ

Vào Thứ Năm, ngày 07 tháng 4 năm 2016, Nguyễn Tất Thắng <
notifications@github.com> đã viết:
