### ISSUE TITLE
Lỗi ngày ở trong danh sách văn bản, ngày  ban hành bị trừ đi 1 ngày!

### ISSUE THREAD

**Issue by ngoctu2008** [nukeviet/module-laws#11]
Lỗi ngày ở trong danh sách văn bản, ngày ban hành bị trừ đi 1 ngày!
![1](https://cloud.githubusercontent.com/assets/9164986/15824141/ee8865c4-2c27-11e6-9e95-3682d5527ef9.jpg)
![2](https://cloud.githubusercontent.com/assets/9164986/15824142/ee88e300-2c27-11e6-98d4-cfc46999e6f4.jpg)

**Comment by hoaquynhtim99** [comment]
Cái này khá lạ, mình check không ra lỗi

**Comment by hoaquynhtim99** [comment]
Cái này đã lâu không có phản hồi và kiểm tra không thấy lỗi mình xin đóng lại, nếu có vấn đề khác bạn vui lòng tạo Issue mới
