### ISSUE TITLE
Lỗi phần "Văn bản liên quan (ID)". không hoạt động

### ISSUE THREAD

**Issue by vingheo** [nukeviet/module-laws#12]
Mình sài bản mới nhất laws 4.1: Phần "Văn bản liên quan (ID)" bị lỗi. không hoạt động

**Comment by hoaquynhtim99** [comment]
Cảm ơn bạn lỗi đã được sửa: https://github.com/nukeviet/module-laws/commit/22eed838913fc23cc60d224be8f253916c6c3b2b
