### ISSUE TITLE
Bổ sung thêm cột ở module laws

### ISSUE THREAD

**Issue by tuanireb** [nukeviet/module-laws#17]
Hầu hết tất cả các cơ quan đều có công văn đến nên phải có cột "ngày đến". Module law chưa có cột này. Hy vọng trong bản cập nhật module thêm chức năng này.

**Comment by vuthao** [comment]
@tuanireb đây là module quản lý văn bản.
Bạn đang nhắc đến module quản lý công văn, bạn tìm module phù hợp để thay thế nhé.
