### ISSUE TITLE
Modun laws bi lỗi phân trang ngoài site

### ISSUE THREAD

**Issue by vingheo** [nukeviet/module-laws#18]
Khi nhấp chuyển trang ngoài site modun laws báo lỗi 404

**Comment by hoaquynhtim99** [comment]
Hiện tại không thấy lỗi này đối với NukeViet 4.1.02, nếu dùng NukeViet thấp hơn thử nâng cấp NukeViet và laws lên bản mới nhất

**Comment by ThinhNguyenVB** [comment]
Lỗi này bản 4.3 không có nhé

**Comment by vingheo** [comment]
ok
