### ISSUE TITLE
Lỗi dư khoảng trống ở cuối Block trong module Laws

### ISSUE THREAD

**Issue by nukevietlan2012** [nukeviet/module-laws#2]
Mỗi Block bị dư 1 ô cuối dùng (phiên bản 3.4.01) như file đính kèm. Nhờ hướng dẫn để xóa dùm. Em cảm ơn!
![loi laws](https://cloud.githubusercontent.com/assets/18258786/14270319/368e7ca6-fb17-11e5-90a7-fdff3af1cec2.jpg)

**Comment by vuthao** [comment]
Đây không phải là lỗi bạn, mà do thiết kế giao diện của bản 3.4 nó như thế. 
Hiện tại chúng tôi dừng không phát triển cho NukeViet 3.4, để tập trung làm cho bản NukeViet 4
