### ISSUE TITLE
Bổ sung thêm chức năng cho gom nhóm văn bản cho modun laws

### ISSUE THREAD

**Issue by vingheo** [nukeviet/module-laws#21]
Hiện tại mình thấy phần: văn bản liên quan phải nhập ID, nếu có nhiều văn bản thì hơi bất tiện và một điều nữa nếu chúng ta tạo modun ảo từ modun laws thì không thể nhập ID giữa các modun ảo và modun gốc. Mình có ý kiến thế này: Chúng ta vẫn giữ nguyên cách nhập ID như cũ nhưng bổ sung thêm mục Nhóm văn bản (đại loại nó giống như mục: theo dòng sự kiện của modun news vậy). Nếu làm được cái này thì hay hơn.
VD: mình có nhiều văn bản nói về **ngân sách 2017** chẳng hạn nằm giải rác ở các modun ảo và modun gốc. Mình sẽ tạo một nhóm văn bản là **ngân sách 2017**, lúc này các văn bản sẽ gom lại. Nói chung quy lại là nó giống như mục theo dòng sự kiện của modun news.

**Comment by vuthao** [comment]
Nguyên tắc thiết kế của NukeViet là các module hoạt động độc lập tòan bộ bạn.
Module ảo cũng có tính năng y như modulle thật, nên được kế thừa.

Theo mình bạn nên tạo ra nhiều chuyên mục thay vì tạo nhiều module ảo.
