### ISSUE TITLE
Modun laws lỗi quả tìm kiếm bị thừa

### ISSUE THREAD

**Issue by vingheo** [nukeviet/module-laws#22]
Sau khi mình nhập vào từ khóa, số ký hiệu vào mục tìm kiếm văn bản thì cho ra kết quả tìm kiếm như sau:
http://i.imgur.com/2semyD4.jpg
Kết quả tìm kiếm tìm đúng nhưng số lượng văn bản tìm thấy bị gấp đôi lên mặc dù đó chỉ là 1 văn bản. Tiện đây cho mình nói luôn: Chỗ đếm tất ca cơ quan ban hành ko hoạt động.

**Comment by vuthao** [comment]
Phiên bản hiện tại mình không thấy lỗi này @vingheo 

bạn kiểm tra lại dùm nhé.

**Comment by ThinhNguyenVB** [comment]
@vingheo tìm kiếm mình kiểm tra ko bị gì hết bạn nhé
Phần các cơ quan nó là phải nhảy vê main là đúng rồi, chỉ là do cái number ko cần hiển thị. Cái này ko phải là lỗi không hoạt động đâu bạn nhé
