### ISSUE TITLE
Góp ý về cách thể hiện kết quả tìm kiếm văn bản

### ISSUE THREAD

**Issue by vingheo** [nukeviet/module-laws#23]
Hiện tại mình thấy modun laws: kết quả tìm kiếm văn bản sắp xếp theo thữ tự ngày tháng tăng (những văn bản mới hơn thì lại nằm ở cuối danh sách tìm kiếm), cái này hơi bất tiện. Nếu chúng ta chỉnh lại kết quả tìm kiếm (những văn bản mới hơn lên trên thì sẽ hợp lý hơn).

**Comment by vuthao** [comment]
Cảm ơn bạn đã góp ý, mình đã sửa lại tại: https://github.com/nukeviet/module-laws/commit/7fdb52ea9d71db82b97695e497cc3b99989b4071
