### ISSUE TITLE
Lỗi thi thêm văn bản

### ISSUE THREAD

**Issue by vuthao** [nukeviet/module-laws#24]
Khi thêm văn bản, thay vì chọn ngưòi ký, ta nhập người ký văn bản, thao tác này lặp đi lặp lại nó sẽ thêm nhiều người ký văn bản (cùng tên)

**Comment by thehung** [comment]
Vậy cần thêm chức năng gộp người ký nữa :D

**Comment by thuvp1995** [comment]
Khi nhập người kí nếu tên người kí trùng y hệt như người kí đã tồn tại thì js select2 hiện tại đã lấy tên người kí cũ. Lỗi thêm nhiều người trùng tên chỉ xảy ra khi nhập họ tên người kí khác nhau in hoa và in thường thôi.
