### ISSUE TITLE
Lỗi thời Ngày ban hành văn bản

### ISSUE THREAD

**Issue by vingheo** [nukeviet/module-laws#28]
Theo hợp lý thì Ngày ban hành văn bản phải luôn luôn trước hoặc bằng Ngày hiệu lực. Nhưng sao mình thấy không có ràng buộc, thích nhập ngày nào thì nhập. Nhập ngày ban hành sau ngày hiệu lực vẫn vậy. Và ngày hết hiệu lực nữa.

**Comment by vuthao** [comment]
Khi thêm mặc định ngày văn bản điền luôn ngày hiện tại để không mất công chọn
