### ISSUE TITLE
Modun không tương thích trên trên NV 4.3

### ISSUE THREAD

**Issue by vingheo** [nukeviet/module-laws#39]
E nâng cấp lên NV 4.3 thì modun laws ko tương thích bị trắng trang, E thấy modun news 4.3 có mục thay đổi thứ tự bài viết rất hay. Mong sao modun laws được như thế này thì hay quá.

**Comment by vuthao** [comment]
Nếu bạn nâng  cấp bằng tay thì cần cập nhật thêm các đoạn CSDL theo hướng dẫn tại đây: https://github.com/nukeviet/module-laws/wiki/Chi-ch%C3%BA-ph%C3%A1t-tri%E1%BB%83n-4.3

**Comment by vingheo** [comment]
E sài tự động

**Comment by vingheo** [comment]
Có gói Cập nhật riêng của modun laws không Anh

**Comment by ThinhNguyenVB** [comment]
@vingheo đây nhé bạn: https://github.com/nukeviet/module-laws/tree/to-4.3.00
