### ISSUE TITLE
Lỗi phân trang khi không có nội dung và sai link phân trang

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/module-laws#47]
Hiện tại bản 4.3 lỗi vấn đề điều hướng như sau
- Ở page 2 có dữ liệu điều chỉnh url page thành pages-2 thì nhảy nội dung về page một -> đúng ra là 404 hoặc chuyển hướng về page đầu
- Ở page 3 trở đi không có dữ liệu vẫn nhảy về page 1 -> đúng ra là ra 404 hoặc chuyển hướng về page đầu

**Comment by ThinhNguyenVB** [comment]
Fixed: https://github.com/nukeviet/module-laws/pull/48/commits/e6fd2509982de972388b5a170efc6252070114ef

**Comment by hoaquynhtim99** [comment]
Phần này đã sửa ở https://github.com/nukeviet/module-laws/commit/4adcdd953897f55d9999b488c81e8b365f890e99
