### ISSUE TITLE
Help không hiển thị nội dung văn bản

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/module-laws#55]
Mình dùng trên bản nv 4.3.00
Module Law phiên bản:  4.1.02-27/01/2018
khi xem trước file PDF thì nội dung không hiển thị. không biết lỗi do đâu? mòng được hướng dẫn pix
Thank!
![law](https://user-images.githubusercontent.com/11238423/37942707-b14343c2-319e-11e8-97cb-e3b219684482.png)

**Comment by vingheo** [comment]
https://nukeviet.vn/vi/forum/Huong-dan-sua-mot-so-loi-o-ban-4-3-00-t43874-p187044/
Xóa hết cache trình duyệt.

**Comment by hoanglongvnpt** [comment]
Thank ban!



*CÔNG NGHỆ WEB SỐ  Add: 28 Phạm Đình Hổ-Thành phố Đông hà-Tỉnh Quảng trịHot
Line: 0913 485 675*


Vào Th 4, 28 thg 3, 2018 vào lúc 08:53 vingheo <notifications@github.com>
đã viết:
