### ISSUE TITLE
Góp ý thêm về chức năng tìm kiếm nâng cao

### ISSUE THREAD

**Issue by vingheo** [nukeviet/module-laws#56]
Khi chúng ta tìm kiếm nâng cao chọn các điều kiện như: **Lĩnh vực, tình trạng, người ký, cơ quan ban hành** thì phải click chuột cho xổ xuống để chọn. Đối với mục **Lĩnh vực, tình trạng, cơ quan ban hành** thì số lượng ít thì có thể chọn được nhưng đối với mục **Người ký** thì bất cập (vì người ký sẽ tăng theo thời gian khi chúng ta kéo chuột để tìm chọn người ký sẽ rất lâu). Mình thấy trong phần Admin khi chọn người ký chỉ cần đánh tên thì menu xổ ra chọn rất nhanh, liệu mình cố thể thêm như vậy ở ngoài cho mục chọn người ký để tìm kiếm nâng cao được không ad.

**Comment by hoaquynhtim99** [comment]
Added: https://github.com/nukeviet/module-laws/commit/e65d4125d9520f657e581794c10448e9a88892c3
