### ISSUE TITLE
Thay thế một giá trị rỗng bằng {LANG.feature}

### ISSUE THREAD

**Issue by NukeVlad** [nukeviet/module-laws#57]
/themes/admin_default/modules/laws/ :
tập tin examine.tpl đường dây 84 <th style="width:120px">{LANG.feature}</th>
tập tin subject.tpl đường dây 128 <th style="width:120px">{LANG.feature}</th>
tập tin cat.tpl đường dây 150 <th>{LANG.feature}</th>
tập tin area.tpl đường dây 149 <th style="width:130px">{LANG.feature}</th>

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/nukeviet/module-laws/commit/6bc898abc0d7a7222ddbbc7a5a1c33cdb0a93b03
