### ISSUE TITLE
Báo lỗi module Law RC3

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/module-laws#6]
Trong admin phần thêm văn bản mình đã chọn 2 văn bản thuộc phần Giáo dục. Nhưng khi ra trang chủ kích hoạt block MODULE BLOCK AREA thì nó nhận sai địa chỉ và không đúng với số lượng văn bản trong chuyên mục "Giáo dục
![112](https://cloud.githubusercontent.com/assets/11238423/15207465/af196ee6-1850-11e6-8cd7-19d3f04d1205.png)
![111](https://cloud.githubusercontent.com/assets/11238423/15207470/b285fdec-1850-11e6-950d-b77933b91ba2.png)
Rất mong được pix sơm. Thank !
"

**Comment by hoaquynhtim99** [comment]
Lỗi gì bạn nhỉ?

**Comment by anhyeuviolet** [comment]
Cái này phải là block block_top10_area mới đúng.
Và nó sai trong file PHP dòng INNER JOIN
```
				$sql = "SELECT COUNT(*) FROM " . NV_PREFIXLANG . "_" . $module_data . "_row t1 INNER JOIN " . NV_PREFIXLANG . "_" . $module_data . "_row_area t2 ON t1.id=t2.row_id WHERE" . $in . " AND status=1";
```
Thiếu 
```
ON t1.id=t2.row_id
```
nên đếm số lượng sai tà la hết. Mình hôm nay thấy tận mấy lỗi, để fix hết rồi up ả thể.

**Comment by hoanglongvnpt** [comment]
Trong phần quản lý lĩnh vực không thể xóa được lĩnh vực, bạn xem pix luôn nhé.

**Comment by anhyeuviolet** [comment]
Mình sửa code trên máy ròi. Mai up lên.


Vào 15-05-2016 21:00, "Nguyễn Tất Thắng" <notifications@github.com> đã viết:
>
> Trong phần quản lý lĩnh vực không thể xóa được lĩnh vực, bạn xem pix luôn
nhé.
