### ISSUE TITLE
Lỗi hiển thị block tìm kiếm

### ISSUE THREAD

**Issue by thehung** [nukeviet/module-laws#62]
Click "Nâng cao" không hiển thị các trường dữ liệu nâng cao (tự thu lại rất nhanh): https://dauthau.info/van-ban-dau-thau/

**Comment by hoaquynhtim99** [comment]
Cái này do site https://dauthau.info/ sử dụng block TÌM KIẾM GÓI THẦU có nút tìm nâng cao trùng với ID của tìm nâng cao văn bản nên xảy ra 2 lần click => Cái này site https://dauthau.info/ phải tự sửa
