### ISSUE TITLE
Cần đưa menu thêm người ký văn bản vào mục quản lý người ký văn bản

### ISSUE THREAD

**Issue by thehung** [nukeviet/module-laws#65]
Để đồng nhất việc quản lý các module, cần đưa menu "thêm người ký văn bản" thành một nút trong mục quản lý "người ký văn bản" (đưa lên trên cùng thay vì dưới cùng như các phần khác.
![image](https://user-images.githubusercontent.com/1892900/54483433-6098fd00-4885-11e9-9233-6049f51c5063.png)

**Comment by hoaquynhtim99** [comment]
Phần này đã được bổ sung

**Comment by thehung** [comment]
Có nút rồi thì mình bỏ cái menu "thêm người ký văn bản" bên cột menu bên trái đi em ơi!

**Comment by hoaquynhtim99** [comment]
Em đã bỏ https://github.com/nukeviet/module-laws/commit/45c276096dca5cedc37b3e5cc3ba84049ac39afb
