### ISSUE TITLE
Lỗi tên mục phân quyền: Quản lý cơ quan ban hành 

### ISSUE THREAD

**Issue by thehung** [nukeviet/module-laws#66]
Tên mục  phân quyền: Quản lý cơ quan ban hành (xem ảnh)
![image](https://user-images.githubusercontent.com/1892900/54483489-64794f00-4886-11e9-9e7d-ee85969dde29.png)

**Comment by hoaquynhtim99** [comment]
Em chưa rõ cái này lỗi gì?

**Comment by thehung** [comment]
Ah. Cái này anh hiểu nhầm. Ko phải lỗi.
