### ISSUE TITLE
Phân bổ chiều rộng cột chưa hợp lý

### ISSUE THREAD

**Issue by thehung** [nukeviet/module-laws#67]
Cột Ngày ban hành đang rộng quá, trong khi cột Trích yếu lại chật quá:
![image](https://user-images.githubusercontent.com/1892900/54483523-0600a080-4887-11e9-9a5c-660a3bb6d55f.png)
(Cấu hình/ Phương án hiển thị: Phân theo cơ quan ban hành)

**Comment by hoaquynhtim99** [comment]
Phần này đã được viết lại giao diện tối ưu hơn
