### ISSUE TITLE
Lỗi: Không có văn bản vẫn đếm là có

### ISSUE THREAD

**Issue by thehung** [nukeviet/module-laws#68]
Lỗi xuất hiện khi Cấu hình/ Phương án hiển thị: Phân theo cơ quan ban hành. Mục bị lỗi là "Bộ GD&ĐT" (Xem hình)
![image](https://user-images.githubusercontent.com/1892900/54483535-39432f80-4887-11e9-9e9b-452b22641aff.png)

**Comment by hoaquynhtim99** [comment]
Lỗi này đã sửa xong. Đối với các cơ quan ban hành bị lỗi chỉ cần thêm mới văn bản vào hoặc xóa văn bản hoặc thay đổi hoạt động của văn bản thuộc cơ quan ban hành đó để cập nhật lại thống kê chính xác
